language: java
script: mvn clean verify -f bundles/fr.univnantes.alma.releng/pom.xml
jdk: oraclejdk8
deploy:
  provider: releases
  file_glob: true
  file: bundles/fr.univnantes.alma.repository/target/products/ALMAServer-*.zip
  on:
repo: alma2015eo/alma2015eo
tags: true
all_branches: false
